---
kind: pipeline
type: docker
name: shellcheck-bash

platform:
  os: linux
  arch: amd64

steps:
- name: shellcheck-bash
  image: koalaman/shellcheck-alpine:stable
  pull: if-not-exists
  commands:
  - shellcheck -S warning -e SC1090 .bashrc
  - shellcheck -S warning .bash/*
  when:
    branch: master