---
kind: pipeline
type: docker
name: shellcheck

platform:
  os: linux
  arch: amd64

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine:stable
  commands:
  - shellcheck --shell bash -S warning .bashrc
  - shellcheck --shell bash -S warning .bash/*
  when:
    event:
      - cron
      target:
        include:
        - monthly