#!/usr/bin/env bash

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
  HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
  shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
  HISTFILE=~/.bash_history
  HISTSIZE=5000
  HISTFILESIZE=5000

# utf8 locale support
  export LANG=en_US.UTF-8
  export LC_CTYPE=en_US.UTF-8
  export LC_ALL=en_US.UTF-8

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
  shopt -s checkwinsize

# disable software flow control so C-s doesn't enable terminal scroll lock, in turn requiring C-q
  stty -ixon

log_debug "00-options custom bash options set"
