#!/usr/bin/env bash

# shellcheck disable=2139
true

# advice on using which, whence, and other shell built in functions
# https://unix.stackexchange.com/a/85250

# set default variables
  TTY_COLOR=""
  GNU_TTY_COLOR=""
  GNU_PRESERVE=""
  GNU=""

# create aliases to sudo and doas so that aliases can be run via sudo and doas
  if command -v sudo > /dev/null 2>&1; then
    alias sudo='sudo '
  fi
  if command -v doas > /dev/null 2>&1; then
    alias doas='doas '
  fi

# detect if tty color support is installed
  if command -v dircolors > /dev/null 2>&1; then
    TTY_COLOR="--color=tty"
    GNU_TTY_COLOR="--color=tty"
  fi

# detect if gnu coreutils are installed
  if command gdircolors > /dev/null 2>&1; then
    GNU_TTY_COLOR="--color=tty"
    GNU_PRESERVE="--preserve-root"
    GNU="g"
  fi

# directory management
  alias ..="cd .."
  alias cd..="cd .."

# set aliases which are dependent on the gnu version binaries
  if [ -z "${GNU}" ]; then
    # ls aliases
    alias ls="$(which ls)"' -F '"${GNU_TTY_COLOR}"
    alias lsa="$(which ls)"' -lah '"${GNU_TTY_COLOR}"
    alias l="$(which ls)"' -la '"${GNU_TTY_COLOR}"
    alias ll="$(which ls)"' -l '"${GNU_TTY_COLOR}"
    alias la="$(which ls)"' -lA --group-directories-first '"${GNU_TTY_COLOR}"
    alias ls.="$(which ls)"' -d .* '"${GNU_TTY_COLOR}"
    # add confrimation on mass changes
    alias mv="$(which mv)"' -i'
    alias cp="$(which cp)"' -i'
    # ln on openbsd doesn't have -i option, set only on linux systems
    if [[ $(uname) == 'Linux' ]]; then
      alias ln="$(which ln)"' -i'
    fi
    # prompt if changing perms or owner on more than 3 files at a time
    alias chown="$(which chown)"' '"${GNU_PRESERVE}"
    alias chmod="$(which chmod)"' '"${GNU_PRESERVE}"
    alias chgrp="$(which chgrp)"' '"${GNU_PRESERVE}"
  else
    # ls aliases
    alias ls="$(which gls)"' -F '"${GNU_TTY_COLOR}"
    alias lsa="$(which gls)"' -lah '"${GNU_TTY_COLOR}"
    alias l="$(which gls)"' -la '"${GNU_TTY_COLOR}"
    alias ll="$(which gls)"' -l '"${GNU_TTY_COLOR}"
    alias la="$(which gls)"' -lA --group-directories-first '"${GNU_TTY_COLOR}"
    alias ls.="$(which gls)"' -d .* '"${GNU_TTY_COLOR}"
    # promt on mass file changes
    alias mv="$(which gmv)"' -i'
    alias cp="$(which gcp)"' -i'
    alias ln="$(which gln)"' -i'
    # prompt if changing perms or owner on more than 3 files at a time
    alias chown="$(which gchown)"' '"${GNU_PRESERVE}"
    alias chmod="$(which gchmod)"' '"${GNU_PRESERVE}"
    alias chgrp="$(which gchgrp)"' '"${GNU_PRESERVE}"
  fi

# grep options
  # detect if gnu grep is installed, otherwise alias regular names
  if command -v ggrep > /dev/null 2>&1; then
    alias grep="$(which ggrep)"' --color=tty'
    alias fgrep="$(which gfgrep)"' --color=tty'
    alias egrep="$(which gegrep)"' --color=tty'
  elif [[ $(uname) == 'Linux' ]]; then
    alias grep="$(which grep)"' '"${TTY_COLOR}"
    alias fgrep="$(which fgrep)"' '"${TTY_COLOR}"
    alias egrep="$(which egrep)"' '"${TTY_COLOR}"
  fi

# ssh
  # alias ssh to change the term to xterm before the session starts
  alias ssh='TERM=xterm ssh'

# who
  # show user idle time
  alias who='who -u'

# htop
  if command -v htop > /dev/null 2>&1; then
    alias top="$(which htop)"
  fi

# diff
  if command -v colordiff > /dev/null 2>&1; then
    alias diff="$(which colordiff)"
  fi

# wget
  # enable continue of downloads
  if command -v wget > /dev/null 2>&1; then
    alias wget="$(which wget)"' -c'
  fi

# tar
  if command -v tar > /dev/null 2>&1; then
    alias untar="$(which tar)"' -zxvf'
  fi

# most
  if command -v most > /dev/null 2>&1; then
    PAGER="$(which most)"
    export PAGER
  fi

# rsync
  if command -v rsync > /dev/null 2>&1; then
    alias rsync-copy="$(which rsync)"' -avzh --progress --stats'
    alias rsync-mirror="$(which rsync)"' -avzh --progress --stats --delete-before --delete-excluded'
    alias rsync-move="$(which rsync)"' -avzh --progress --stats --remove-source-files'
    alias rsync-synchronize="$(which rsync)"' -avzuh --progress --stats --delete'
    alias rsync-update="$(which rsync)"' -avzuh --progress --stats'
  fi

# cli to online paste aliases
  alias termbin='nc termbin.com 9999'
  alias clibin='curl -q -F "clbin=<-" https://clbin.com; echo Append "?hl" to the url for highlighting'
  alias pastebin=clibin

# grep output for lines without common comment
  alias nocomments='grep -Evi '\''^( *)(#|$|;|//|--|rem|::|\"|\|\|)'\'''
  alias comments='grep -Ei '\''^(#|;|//|--|rem|::|\"|\|\|)'\'''

# dmesg
  if [[ $(uname) == 'Linux' ]]; then
    alias dmesg='dmesg -L auto -T'
  fi

# disk, partition, folder and file usage commands
  # disk usage in the current directory
  alias usagedirectory="$(which du)"' -ch 2> /dev/null | tail -1'

  # total disk usage
  alias usagedisk="$(which df)"' -hl --total | tail -1'

  # individual partition usages without the temporary memory values
  alias usagepartition="$(which df)"' -hlT --exclude-type=tmpfs --exclude-type=devtmpfs'

  # largest folders within current dir
  function usagehogs {
    du -k ./* 2>/dev/null | sort -nr | awk '{ if($1>=1024*1024) {size=$1/1024/1024; unit="G"} else if($1>=1024) {size=$1/1024; unit="M"} else {size=$1; unit="K"}; if(size<10) format="%.1f%s"; else format="%.0f%s"; res=sprintf(format,size,unit); printf "%-8s %s\n",res,$2 }'
  }

# unset variables
  unset TTY_COLOR
  unset GNU_TTY_COLOR
  unset GNU_PRESERVE
  unset GNU
